spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    fashionable:
      simba:
        yanawaserver: debug
feign:
  client:
    config:
      default:
        logger-level: FULL
