spring:
  profiles:
    active: dep

security:
  jwt:
    token:
      secret-key: yanawa-secret-key
      refresh-key: yanawa-refresh-key
      validity-access-token-milliseconds: 1800000
      validity-refresh-token-milliseconds: 7200000
kakao:
  client:
    client-id: 8c8c60e9c505e9fd8b8b7aa6aaa82874
    secret-key: yFyDcPvqlczkWdRBFlnbvsjd0mzlmCX6
    redirect-uri: http://13.125.243.184:80/kakao/login/callback
