spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://yanawa-server.cemcoksbd5o4.ap-northeast-2.rds.amazonaws.com:3306/yanawa?serverTimezone=Asia/Seoul
    username: spear
    password: this-is-spear
    driver-class-name: com.mysql.cj.jdbc.Driver
